import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import {Metal} from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metal = Metal({subsets:["latin"] , weight: ["400"]},)

export const metadata = {
  title: "Unsplash Copy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav>
          <Link href={'/'}></Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
